# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: "Ubuntu-16.04"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      npm install
      npm test
    workingDirectory: "$(Build.SourcesDirectory)/backend"
    displayName: "npm install and test"

  - script: |
      npm run build
    workingDirectory: "$(Build.SourcesDirectory)/backend"
    displayName: "build"

  - task: AzureRmWebAppDeployment@3
    inputs:
      azureSubscription: "azure_connection"
      WebAppName: "dm-tools"
      Package: "$(Build.SourcesDirectory)/backend"
      GenerateWebConfig: true
      WebConfigParameters: "-Handler iisnode -NodeStartFile build/server.js -appType node"
